package arayüz;

import static arayüz.alan.arsabilgi;
import static arayüz.alan.kullanici;
import baglanti.database;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import veritabani.Kullanici;

public class arsabilgi extends javax.swing.JPanel {

    public static boolean sayac = false;
    public static boolean calis = false;
    public static boolean vardiyasayac = false;
    private database bglnt = new database();

    public arsabilgi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        alannotxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        alanturutxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        alansahibitxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        magazailanbtn = new javax.swing.JButton();
        emlakilanbtn = new javax.swing.JButton();
        ozelilanbtn = new javax.swing.JButton();
        marketilanbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ucrettxt = new javax.swing.JTextField();
        digergunbtn = new javax.swing.JButton();
        tarihatlabtn = new javax.swing.JButton();
        zamanbar = new javax.swing.JProgressBar(0,2000);
        vardiyabaslabtn = new javax.swing.JButton();
        alisverisbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(229, 213, 234));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), null));

        jPanel1.setBackground(new java.awt.Color(229, 213, 234));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setText("ALAN NO : ");

        alannotxt.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        alannotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alannotxtActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel7.setText("ALAN TÜRÜ : ");

        alanturutxt.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        alanturutxt.setText(" ");
        alanturutxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alanturutxtActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel8.setText("  ALAN SAHİBİ: ");

        alansahibitxt.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        alansahibitxt.setText(" ");

        jLabel12.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel12.setText("ALAN BİLGİLERİ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alanturutxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alannotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(alansahibitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(91, 91, 91))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alannotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alanturutxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alansahibitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(229, 213, 234));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Snap ITC", 0, 24)); // NOI18N
        jLabel2.setText("İLANLAR");

        magazailanbtn.setBackground(new java.awt.Color(255, 204, 153));
        magazailanbtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        magazailanbtn.setText("MAĞAZA");
        magazailanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magazailanbtnActionPerformed(evt);
            }
        });

        emlakilanbtn.setBackground(new java.awt.Color(255, 153, 153));
        emlakilanbtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        emlakilanbtn.setText("EMLAK");
        emlakilanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emlakilanbtnActionPerformed(evt);
            }
        });

        ozelilanbtn.setBackground(new java.awt.Color(14, 225, 194));
        ozelilanbtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        ozelilanbtn.setText("ÖZEL İŞLETME");
        ozelilanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ozelilanbtnActionPerformed(evt);
            }
        });

        marketilanbtn.setBackground(new java.awt.Color(204, 255, 204));
        marketilanbtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        marketilanbtn.setText("MARKET");
        marketilanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marketilanbtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setText("Yönetici İlanlarının ");

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setText("Günlük Ücreti : ");

        ucrettxt.setEditable(false);
        ucrettxt.setBackground(new java.awt.Color(229, 213, 234));
        ucrettxt.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        ucrettxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ucrettxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(emlakilanbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(magazailanbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(marketilanbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ozelilanbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(ucrettxt, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(emlakilanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(magazailanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(marketilanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ozelilanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(ucrettxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        digergunbtn.setBackground(new java.awt.Color(105, 146, 220));
        digergunbtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        digergunbtn.setText("DİĞER GÜN");
        digergunbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digergunbtnActionPerformed(evt);
            }
        });

        tarihatlabtn.setBackground(new java.awt.Color(224, 9, 136));
        tarihatlabtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        tarihatlabtn.setText("TARİH ATLA");
        tarihatlabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarihatlabtnActionPerformed(evt);
            }
        });

        zamanbar.setValue(0);
        zamanbar.setStringPainted(true);
        zamanbar.setBackground(new java.awt.Color(204, 204, 204));
        zamanbar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        zamanbar.setForeground(new java.awt.Color(255, 153, 102));

        vardiyabaslabtn.setBackground(new java.awt.Color(0, 153, 153));
        vardiyabaslabtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        vardiyabaslabtn.setText("Vardiyaya Başla");
        vardiyabaslabtn.setBorder(null);
        vardiyabaslabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vardiyabaslabtnActionPerformed(evt);
            }
        });

        alisverisbtn.setBackground(new java.awt.Color(125, 63, 156));
        alisverisbtn.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        alisverisbtn.setText("ALIŞVERİŞ");
        alisverisbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alisverisbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zamanbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(alisverisbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(digergunbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tarihatlabtn)
                        .addGap(36, 36, 36))))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(vardiyabaslabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tarihatlabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(digergunbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(zamanbar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vardiyabaslabtn, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(alisverisbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(370, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void alannotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alannotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alannotxtActionPerformed

    private void alanturutxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alanturutxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alanturutxtActionPerformed

    private void magazailanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_magazailanbtnActionPerformed
        if (sayac != true) {
            int sec;
            String secim;
            alan ekran = new alan("");
            String vardiyalar[] = {"Vardiya 1(00.00-08.00)", "Vardiya 2(08.00-16.00)", "Vardiya 3(16.00-00.00)"};

            JComboBox cb = new JComboBox(vardiyalar);

            sec = JOptionPane.showConfirmDialog(this, cb, "Çalışmak İstediğiniz Vardiyayı Seçiniz", JOptionPane.DEFAULT_OPTION);
            secim = (String) cb.getSelectedItem();
            String str = JOptionPane.showInputDialog("Çalışmak İstediğiniz Gün Sayısını Giriniz:");
            int gun = Integer.parseInt(str);

            ekran.calismabilgilerial(secim, 2, gun);
            ekran.calisantable();
            ekran.calismabilgileri();


    }//GEN-LAST:event_magazailanbtnActionPerformed
    }
    private void emlakilanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emlakilanbtnActionPerformed

        Kullanici kullanici = new Kullanici();
        int sec;
        String secim;
        alan ekran = new alan("");
        String vardiyalar[] = {"Vardiya 1(00.00-08.00)", "Vardiya 2(08.00-16.00)", "Vardiya 3(16.00-00.00)"};

        JComboBox cb = new JComboBox(vardiyalar);

        sec = JOptionPane.showConfirmDialog(this, cb, "Çalışmak İstediğiniz Vardiyayı Seçiniz", JOptionPane.DEFAULT_OPTION);
        secim = (String) cb.getSelectedItem();

        String str = JOptionPane.showInputDialog("Çalışmak İstediğiniz Gün Sayısını Giriniz:");
        int gun = Integer.parseInt(str);

        ekran.calismabilgilerial(secim, 1, gun);
        ekran.calisantable();
        ekran.calismabilgileri();


    }//GEN-LAST:event_emlakilanbtnActionPerformed

    private void ozelilanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ozelilanbtnActionPerformed


    }//GEN-LAST:event_ozelilanbtnActionPerformed

    private void marketilanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marketilanbtnActionPerformed
        if (sayac != true) {
            int sec;
            String secim;
            alan ekran = new alan("");
            String vardiyalar[] = {"Vardiya 1(00.00-08.00)", "Vardiya 2(08.00-16.00)", "Vardiya 3(16.00-00.00)"};

            JComboBox cb = new JComboBox(vardiyalar);

            sec = JOptionPane.showConfirmDialog(this, cb, "Çalışmak İstediğiniz Vardiyayı Seçiniz", JOptionPane.DEFAULT_OPTION);
            secim = (String) cb.getSelectedItem();
            String str = JOptionPane.showInputDialog("Çalışmak İstediğiniz Gün Sayısını Giriniz:");

            int gun = Integer.parseInt(str);

            ekran.calismabilgilerial(secim, 3, gun);
            ekran.calisantable();
            ekran.calismabilgileri();

    }//GEN-LAST:event_marketilanbtnActionPerformed
    }


    private void digergunbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digergunbtnActionPerformed

        alan ekran = new alan("");
        ekran.digergun(1);
        ekran.buton();
        ekran.kullanicibilgileri();
        ekran.calismabilgileri();
    }//GEN-LAST:event_digergunbtnActionPerformed

    private void tarihatlabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarihatlabtnActionPerformed

        alan ekran = new alan("");
        String str = JOptionPane.showInputDialog("Atlamak İstediğiniz Gün Sayısını Giriniz");
        int gun = Integer.parseInt(str);
        ekran.digergun(gun);
        ekran.buton();
        ekran.kullanicibilgileri();
        ekran.calismabilgileri();
    }//GEN-LAST:event_tarihatlabtnActionPerformed

    private void vardiyabaslabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vardiyabaslabtnActionPerformed

        Connection c = bglnt.dbcon();
        Statement st = null;
        ResultSet rs = null;
        try {
            st = c.createStatement();
            rs = st.executeQuery("SELECT kullanici_calisilacakgun FROM kullanici");
            while (rs.next()) {
                if (rs.getInt("kullanici_calisilacakgun") != 0) {

                    bar bar = new bar();
                    bar.start();

                } else {
                    vardiyasayac = true;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(arsabilgi.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                st.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(arsabilgi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_vardiyabaslabtnActionPerformed

    private void alisverisbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alisverisbtnActionPerformed
        int sec;
        int islem;
        String secim;
        String islem1;
        String str;
        String kiraarsa;
        String kiralama;
        String fiyat;
        alan ekran = new alan("");
        Kullanici kullanici = new Kullanici();
        kullanici = alan.kullanici;
        int a = kullanici.getKullanici_no();
        Connection c = bglnt.dbcon();
        Statement st = null;
        ResultSet rs = null;
        Statement st1 = null;

        if (vardiyasayac == true) {

            String alisveris[] = {"Market", "Emlak", "Mağaza"};

            JComboBox cb = new JComboBox(alisveris);

            sec = JOptionPane.showConfirmDialog(this, cb, "Nereden Alışveriş Yapmak İstiyorsunuz?", JOptionPane.DEFAULT_OPTION);
            secim = (String) cb.getSelectedItem();
            if ((secim.equalsIgnoreCase("Market")) || (secim.equalsIgnoreCase("Mağaza"))) {

                str = JOptionPane.showInputDialog("Birim Fiyatı 3 TL dir. Ne Kadar Almak İstiyorsunuz?");

                int miktar = Integer.parseInt(str);
                int yemek, para, esya;

                try {
                    st = c.createStatement();
                    st1 = c.createStatement();
                    rs = st.executeQuery("SELECT * FROM kullanici");
                    while (rs.next()) {
                        if (kullanici.getKullanici_no() == rs.getInt("kullanici_no")) {
                            yemek = rs.getInt("kullanici_yemek") + (miktar);
                            esya = rs.getInt("kullanici_esya") + (miktar);
                            para = rs.getInt("kullanici_para") - (miktar * 3);
                            if (secim.equalsIgnoreCase("Market")) {
                                st1.executeUpdate("UPDATE kullanici SET kullanici_yemek= '" + yemek + "',kullanici_para='" + para + "' WHERE kullanici_no='" + a + "'");
                            } else if (secim.equalsIgnoreCase("Mağaza")) {
                                st1.executeUpdate("UPDATE kullanici SET kullanici_esya= '" + esya + "' ,kullanici_para='" + para + "'  WHERE kullanici_no='" + a + "' ");
                            }

                        }
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(arsabilgi.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {c.close();
                        st.close();
                        st1.close();
                        rs.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(arsabilgi.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
        }

        ekran.kullanicibilgileri();

    }//GEN-LAST:event_alisverisbtnActionPerformed

    private void ucrettxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ucrettxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ucrettxtActionPerformed
    public class bar extends Thread {

        @Override
        public void run() {

            vardiyasayac = false;
            for (int i = 0; i <= 2000; i = i + 20) {
                try {
                    zamanbar.setValue(i);
                    Thread.sleep(100);
                } catch (InterruptedException ex) {
                    Logger.getLogger(arsabilgi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            vardiyasayac = true;

            zamanbar.setValue(0);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField alannotxt;
    public javax.swing.JTextField alansahibitxt;
    public javax.swing.JTextField alanturutxt;
    public javax.swing.JButton alisverisbtn;
    public javax.swing.JButton digergunbtn;
    public javax.swing.JButton emlakilanbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JButton magazailanbtn;
    public javax.swing.JButton marketilanbtn;
    public javax.swing.JButton ozelilanbtn;
    private javax.swing.JButton tarihatlabtn;
    public javax.swing.JTextField ucrettxt;
    public javax.swing.JButton vardiyabaslabtn;
    public javax.swing.JProgressBar zamanbar;
    // End of variables declaration//GEN-END:variables
}
