package arayüz;

import baglanti.database;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

public class small extends javax.swing.JPanel {

    private database bglnt = new database();

    public small() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arsa2btn = new javax.swing.JButton();
        arsa3btn = new javax.swing.JButton();
        arsa4btn = new javax.swing.JButton();
        arsa5btn = new javax.swing.JButton();
        arsa1btn = new javax.swing.JButton();
        arsa7btn = new javax.swing.JButton();
        arsa8btn = new javax.swing.JButton();
        arsa9btn = new javax.swing.JButton();
        arsa6btn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(800, 470));

        arsa2btn.setBackground(new java.awt.Color(255, 204, 153));
        arsa2btn.setText("MAĞAZA");
        arsa2btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arsa2btnActionPerformed(evt);
            }
        });

        arsa3btn.setBackground(new java.awt.Color(204, 255, 204));
        arsa3btn.setText("MARKET");
        arsa3btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arsa3btnActionPerformed(evt);
            }
        });

        arsa4btn.setBackground(new java.awt.Color(235, 184, 110));
        arsa4btn.setText("ARSA");
        arsa4btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arsa4btnActionPerformed(evt);
            }
        });

        arsa5btn.setBackground(new java.awt.Color(235, 184, 110));
        arsa5btn.setText("ARSA");
        arsa5btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arsa5btnActionPerformed(evt);
            }
        });

        arsa1btn.setBackground(new java.awt.Color(255, 153, 153));
        arsa1btn.setText("EMLAK");
        arsa1btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arsa1btnActionPerformed(evt);
            }
        });

        arsa7btn.setBackground(new java.awt.Color(235, 184, 110));
        arsa7btn.setText("ARSA");
        arsa7btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arsa7btnActionPerformed(evt);
            }
        });

        arsa8btn.setBackground(new java.awt.Color(235, 184, 110));
        arsa8btn.setText("ARSA");
        arsa8btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arsa8btnActionPerformed(evt);
            }
        });

        arsa9btn.setBackground(new java.awt.Color(235, 184, 110));
        arsa9btn.setText("ARSA");
        arsa9btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arsa9btnActionPerformed(evt);
            }
        });

        arsa6btn.setBackground(new java.awt.Color(235, 184, 110));
        arsa6btn.setText("ARSA");
        arsa6btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arsa6btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arsa7btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arsa4btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arsa1btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arsa5btn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arsa2btn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arsa8btn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arsa6btn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arsa3btn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arsa9btn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arsa2btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arsa3btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arsa1btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arsa4btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arsa5btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arsa6btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arsa9btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arsa8btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arsa7btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void arsa1btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arsa1btnActionPerformed
        String tur = null;
        String sahip = null;
        alan ekran = new alan("");

        Connection c = bglnt.dbcon();
        Statement st = null;
        ResultSet rs = null;
        try {

            st = c.createStatement();

            rs = st.executeQuery("SELECT * FROM small_arsa_bilgileri");

            while (rs.next()) {
                if (rs.getInt("arsa_no") == 1) {
                    tur = rs.getString("arsa_turu");
                    sahip = rs.getString("arsa_sahibi");
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(small.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                c.close();
                st.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(medium.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        ekran.alanbilgileri(1, tur, sahip);


    }//GEN-LAST:event_arsa1btnActionPerformed

    private void arsa2btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arsa2btnActionPerformed
        String tur = null;
        String sahip = null;
        alan ekran = new alan("");

        Connection c = bglnt.dbcon();
        Statement st = null;
        ResultSet rs = null;
        try {

            st = c.createStatement();

            rs = st.executeQuery("SELECT * FROM small_arsa_bilgileri");

            while (rs.next()) {
                if (rs.getInt("arsa_no") == 2) {
                    tur = rs.getString("arsa_turu");
                    sahip = rs.getString("arsa_sahibi");
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(small.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {c.close();
                st.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(medium.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        ekran.alanbilgileri(2, tur, sahip);


    }//GEN-LAST:event_arsa2btnActionPerformed

    private void arsa3btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arsa3btnActionPerformed
        String tur = null;
        String sahip = null;
        alan ekran = new alan("");

        Connection c = bglnt.dbcon();
        Statement st = null;
        ResultSet rs = null;
        try {

            st = c.createStatement();

            rs = st.executeQuery("SELECT * FROM small_arsa_bilgileri");

            while (rs.next()) {
                if (rs.getInt("arsa_no") == 3) {
                    tur = rs.getString("arsa_turu");
                    sahip = rs.getString("arsa_sahibi");
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(small.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {c.close();
                st.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(medium.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        ekran.alanbilgileri(3, tur, sahip);


    }//GEN-LAST:event_arsa3btnActionPerformed

    private void arsa4btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arsa4btnActionPerformed
        String tur = null;
        String sahip = null;
        alan ekran = new alan("");
        Connection c = bglnt.dbcon();
        Statement st = null;
        ResultSet rs = null;
        try {

            st = c.createStatement();

            rs = st.executeQuery("SELECT * FROM small_arsa_bilgileri");

            while (rs.next()) {
                if (rs.getInt("arsa_no") == 4) {
                    tur = rs.getString("arsa_turu");
                    sahip = rs.getString("arsa_sahibi");
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(small.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {c.close();
                st.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(medium.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        ekran.alanbilgileri(4, tur, sahip);


    }//GEN-LAST:event_arsa4btnActionPerformed

    private void arsa5btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arsa5btnActionPerformed

        String tur = null;
        String sahip = null;
        alan ekran = new alan("");
        Connection c = bglnt.dbcon();
        Statement st = null;
        ResultSet rs = null;
        try {

            st = c.createStatement();

            rs = st.executeQuery("SELECT * FROM small_arsa_bilgileri");

            while (rs.next()) {
                if (rs.getInt("arsa_no") == 5) {
                    tur = rs.getString("arsa_turu");
                    sahip = rs.getString("arsa_sahibi");
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(small.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {c.close();
                st.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(medium.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        ekran.alanbilgileri(5, tur, sahip);


    }//GEN-LAST:event_arsa5btnActionPerformed

    private void arsa6btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arsa6btnActionPerformed

        String tur = null;
        String sahip = null;
        alan ekran = new alan("");

        Connection c = bglnt.dbcon();
        Statement st = null;
        ResultSet rs = null;
        try {

            st = c.createStatement();

            rs = st.executeQuery("SELECT * FROM small_arsa_bilgileri");

            while (rs.next()) {
                if (rs.getInt("arsa_no") == 6) {
                    tur = rs.getString("arsa_turu");
                    sahip = rs.getString("arsa_sahibi");
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(small.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {c.close();
                st.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(medium.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        ekran.alanbilgileri(6, tur, sahip);


    }//GEN-LAST:event_arsa6btnActionPerformed

    private void arsa7btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arsa7btnActionPerformed
        String tur = null;
        String sahip = null;
        alan ekran = new alan("");
        Connection c = bglnt.dbcon();
        Statement st = null;
        ResultSet rs = null;
        try {

            st = c.createStatement();

            rs = st.executeQuery("SELECT * FROM small_arsa_bilgileri");

            while (rs.next()) {
                if (rs.getInt("arsa_no") == 7) {
                    tur = rs.getString("arsa_turu");
                    sahip = rs.getString("arsa_sahibi");
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(small.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {c.close();
                st.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(medium.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        ekran.alanbilgileri(7, tur, sahip);


    }//GEN-LAST:event_arsa7btnActionPerformed

    private void arsa8btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arsa8btnActionPerformed

        String tur = null;
        String sahip = null;
        alan ekran = new alan("");
        Connection c = bglnt.dbcon();
        Statement st = null;
        ResultSet rs = null;
        try {

            st = c.createStatement();

            rs = st.executeQuery("SELECT * FROM small_arsa_bilgileri");

            while (rs.next()) {
                if (rs.getInt("arsa_no") == 8) {
                    tur = rs.getString("arsa_turu");
                    sahip = rs.getString("arsa_sahibi");
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(small.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {c.close();
                st.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(medium.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        ekran.alanbilgileri(8, tur, sahip);


    }//GEN-LAST:event_arsa8btnActionPerformed

    private void arsa9btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arsa9btnActionPerformed
        String tur = null;
        String sahip = null;
        alan ekran = new alan("");
        Connection c = bglnt.dbcon();
        Statement st = null;
        ResultSet rs = null;
        try {

            st = c.createStatement();
            rs = st.executeQuery("SELECT * FROM small_arsa_bilgileri");

            while (rs.next()) {
                if (rs.getInt("arsa_no") == 9) {
                    tur = rs.getString("arsa_turu");
                    sahip = rs.getString("arsa_sahibi");
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(small.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {c.close();
                st.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(medium.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        ekran.alanbilgileri(9, tur, sahip);


    }//GEN-LAST:event_arsa9btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arsa1btn;
    private javax.swing.JButton arsa2btn;
    private javax.swing.JButton arsa3btn;
    private javax.swing.JButton arsa4btn;
    private javax.swing.JButton arsa5btn;
    private javax.swing.JButton arsa6btn;
    private javax.swing.JButton arsa7btn;
    private javax.swing.JButton arsa8btn;
    private javax.swing.JButton arsa9btn;
    // End of variables declaration//GEN-END:variables
}
